### ISSUE TITLE
overview tab name bug

### ISSUE THREAD

**Issue by auckz** [Arziel1992/Z-S-Overview-Pack#3]
when I save a change in the overview tab it creates a new option (even if I save with the same name)
example: http://i.imgur.com/DdsOZTf.png

**Comment by Arziel1992** [comment]
FAQ:

https://github.com/Arziel1992/Z-S-Overview-Pack/blob/master/FAQ.md#if-i-click-save-to-commit-the-changes-the-preset-name-will-not-save-properly

**Comment by auckz** [comment]
Sorry, I can't read ;p

**Comment by auckz** [comment]
Sorry, I can't read ;p
