### ISSUE TITLE
cant find the Z-S PvE Extended pack in eve channel

### ISSUE THREAD

**Issue by raykai** [Arziel1992/Z-S-Overview-Pack#7]
hey im looking for the Z-S PvE Extended pack.

The How to install says its for : Z-S PvE Extended contains presets for Anoms/Ratting, Incursion, Mining, and Show Drones. That's what i need but i cant see it in the list in eve:

![missing](https://user-images.githubusercontent.com/8138894/30893800-1323cfb4-a30e-11e7-8648-ca71e59f90d8.JPG)

i need the mining tab from it.

**Comment by Arziel1992** [comment]
The Advanced is the Extended, I just haven't changed the name in the README file, sorry for the confusion.
